<?php
// @codingStandardsIgnoreFile
// @codeCoverageIgnoreStart
// this is an autogenerated file - do not edit
spl_autoload_register(
    function($class) {
        static $classes = null;
        if ($classes === null) {
            $classes = array(
                'appconfiguration' => '/Factory.php',
                'dbconnection' => '/db/DbConnection.php',
                'factory' => '/Factory.php',
                'passhash' => '/PassHash.php',
                'taskrepository' => '/TaskRepository.php',
                'userrepository' => '/UserRepository.php'
            );
        }
        $cn = strtolower($class);
        if (isset($classes[$cn])) {
            require __DIR__ . $classes[$cn];
        }
    },
    true,
    false
);
// @codeCoverageIgnoreEnd
